### ISSUE TITLE
[BUG] Not working with docker-compose at all

### ISSUE THREAD

**Issue by iocron** [Ekliptor/WolfBot#108]
I only get errors with docker-compose up. It seems like he is looking for the module "../configLocal" which makes no sense to me, neither it's mentioned in the docs / readme: 

wolfbot_1  | 2021-03-24 20:28:57 - info: ***DISCOUNT*** Having trouble setting up WolfBot on your local machine? Try the cloud version at https://wolfbot.org with a 30% discount with this code: gitsource7393
wolfbot_1  | Error: Cannot find module '../configLocal'
wolfbot_1  | Require stack:
wolfbot_1  | - /app/build/src/LoginController.js
wolfbot_1  | - /app/build/src/Trade/AbstractTrader.js
wolfbot_1  | - /app/build/src/Trade/Backtester.js
wolfbot_1  | - /app/build/src/TradeAdvisor.js
wolfbot_1  | - /app/build/src/AI/BudFox.js
wolfbot_1  | - /app/build/src/AI/Brain.js
wolfbot_1  | - /app/build/src/ExchangeController.js
wolfbot_1  | - /app/build/src/Controller.js
wolfbot_1  | - /app/build/app.js
wolfbot_1  |     at Function.Module._resolveFilename (internal/modules/cjs/loader.js:815:15)
wolfbot_1  |     at Function.Module._load (internal/modules/cjs/loader.js:667:27)
wolfbot_1  |     at Module.require (internal/modules/cjs/loader.js:887:19)
wolfbot_1  |     at require (internal/modules/cjs/helpers.js:74:18)
wolfbot_1  |     at Object.<anonymous> (/app/src/LoginController.ts:12:1)
wolfbot_1  |     at Module._compile (internal/modules/cjs/loader.js:999:30)
wolfbot_1  |     at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
wolfbot_1  |     at Module.load (internal/modules/cjs/loader.js:863:32)
wolfbot_1  |     at Function.Module._load (internal/modules/cjs/loader.js:708:14)
wolfbot_1  |     at Module.require (internal/modules/cjs/loader.js:887:19)
wolfbot_1  |     at require (internal/modules/cjs/helpers.js:74:18)
wolfbot_1  |     at Object.<anonymous> (/app/src/Trade/AbstractTrader.ts:20:1)
wolfbot_1  |     at Module._compile (internal/modules/cjs/loader.js:999:30)
wolfbot_1  |     at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
wolfbot_1  |     at Module.load (internal/modules/cjs/loader.js:863:32)
wolfbot_1  |     at Function.Module._load (internal/modules/cjs/loader.js:708:14)
wolfbot_1  |     at Module.require (internal/modules/cjs/loader.js:887:19)
wolfbot_1  |     at require (internal/modules/cjs/helpers.js:74:18)
wolfbot_1  |     at Object.<anonymous> (/app/src/Trade/Backtester.ts:4:1)
wolfbot_1  |     at Module._compile (internal/modules/cjs/loader.js:999:30)
wolfbot_1  |     at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
wolfbot_1  |     at Module.load (internal/modules/cjs/loader.js:863:32)
wolfbot_wolfbot_1 exited with code 1

**Comment by dmncr** [comment]
Hi,

Just got it working by copying the config file and then building the container locally. 
1. Check out the source code
2. Copy the configLocal-sample.ts => configLocal.ts (as per the instructions)
3. Run the run docker-compose up => voila

I just removed the "image: wolfbot-docker/latest" part from the docker-compose file completely. 
Here's how it looks now:

version: "3"
services:
  wolfbot:
    build: .
    restart: unless-stopped
    container_name: wolfbot
    ports:
      - "8331:8331"
      - "8332:8332"
    depends_on:
      - mongodb
  mongodb:
    image: mongo:latest
    container_name: mongodb
    environment:
      - MONGO_DATA_DIR=/data/db
      - MONGO_LOG_DIR=/dev/null
    volumes:
      - /somelocalpathforpersistenmongodbstorage:/data/db

**Comment by psychomantis1904** [comment]
Worked for me. THX.

Now the next one, the WebUI says:
You are not authorized to access this application. Please contact the administrator for an API-Key.

My API-Key from my exchange or what or is it not possible to use without buying subscription from wolfbot webiste?

**Comment by dmncr** [comment]
Nice =)

Yeah, tried removing the pre-set api-key from the configLocal-sample but it still asked for it (after navigating around for a bit). Tried setting my own and sending it as well and didn't work (or I did it the wrong way, not sure). Got stuck here as well for this bot.

**Comment by psychomantis1904** [comment]
> Nice =)
> 
> Yeah, tried removing the pre-set api-key from the configLocal-sample but it still asked for it (after navigating around for a bit). Tried setting my own and sending it as well and didn't work (or I did it the wrong way, not sure). Got stuck here as well for this bot.

Me too and no one wants to help in discord channel :(
I think only the paying people were supported.

**Comment by Ekliptor** [comment]
if you run `docker build` before compose it works with the provided image. otherwise see the suggestion by @dmncr
