### ISSUE TITLE
Run Errors

### ISSUE THREAD

**Issue by pragr** [Ekliptor/WolfBot#115]
Hi,

I am having issues running app.js in the build directory as instructed. Appreciate if you can help.

bitnami@rytend:~/WolfBot/build$ node app.js --debug --config=Noop --trader=RealTimeTrader 
--noUpdate --noBrowser
2021-05-26 07:10:17 - info: ***DISCOUNT*** Having trouble setting up WolfBot on your local
 machine? Try the cloud version at https://wolfbot.org with a 30% discount with this code:
 gitsource7393
/home/bitnami/WolfBot/node_modules/deribit-v2-ws/con.js:62
  ping = async() => {
       ^

SyntaxError: Unexpected token =
    at Module._compile (internal/modules/cjs/loader.js:723:23)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Object.<anonymous> (/home/bitnami/WolfBot/node_modules/deribit-v2-ws/index.js:1:18)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Object.<anonymous> (/home/bitnami/WolfBot/src/Exchanges/Deribit.ts:35:1)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Module.require (internal/modules/cjs/loader.js:692:17)
bitnami@rytend:~/WolfBot/build$

**Comment by Ekliptor** [comment]
your nodejs version is too old. It does not recognize async function syntax. Update to Nodejs >= v14
