### ISSUE TITLE
Error connecting to mongo

### ISSUE THREAD

**Issue by altcnews** [Ekliptor/WolfBot#15]
Hi,

I got this error when running:

2019-03-10 09:49:43 - info: Server is listening on http://bitmex:8331/index.html 
2019-03-10 09:49:43 - info: Server is listening on https://bitmex:8332/index.html
(node:18078) DeprecationWarning: current URL string parser is deprecated, and will be removed in a future version. To use the new parser, pass option { useNewUrlParser: true } to MongoClient.connect.
2019-03-10 09:49:43 - error: Error connecting to MongoDB {"message":"Invalid apiVersion \"5.0\", expected a function or one of _default, 6.6, 6.5, 6.4, 6.3, 6.2, 6.1, 6.0, 5.6, 2.4, 1.7, 0.90, 6.7, 7.0, 7.x, master","stack":"TypeError: Invalid apiVersion \"5.0\", expected a function or one of _default, 6.6, 6.5, 6.4, 6.3, 6.2, 6.1, 6.0, 5.6, 2.4, 1.7, 0.90, 6.7, 7.0, 7.x, master\n    at Object.utils.funcEnum (/usr/lib/node_modules/elasticsearch/src/lib/utils.js:285:13)\n    at new Client (/usr/lib/node_modules/elasticsearch/src/lib/client.js:70:33)\n    at connectSearch (/home/ubuntu/wolfbot/src/database.ts:121:26)\n    at connectOps.push.Promise (/home/ubuntu/wolfbot/src/database.ts:63:13)\n    at new Promise (<anonymous>)\n    at Object.connectAll (/home/ubuntu/wolfbot/src/database.ts:62:25)\n    at Controller.connect (/home/ubuntu/wolfbot/src/Controller.ts:190:12)\n    at Promise (/home/ubuntu/wolfbot/src/Controller.ts:100:18)\n    at new Promise (<anonymous>)\n    at Controller.start (/home/ubuntu/wolfbot/src/Controller.ts:98:16)\n    at Object.<anonymous> (/home/ubuntu/wolfbot/app.ts:271:16)\n    at Module._compile (module.js:653:30)\n    at Object.Module._extensions..js (module.js:664:10)\n    at Module.load (module.js:566:32)\n    at tryModuleLoad (module.js:506:12)\n    at Function.Module._load (module.js:498:3)\n    at Function.Module.runMain (module.js:694:10)\n    at startup (bootstrap_node.js:204:16)\n    at bootstrap_node.js:625:3"}
2019-03-10 09:49:43 - info: Main process exited with code 1

Could you please help?
Thank you.

**Comment by Ekliptor** [comment]
The error is from elasticsearch, not from mongodb.
I use elasticsearch in many other of my projects, but wolfbot currently doesn't need it.
From configLocal.ts:
`"searchHosts": [], // elasticsearch host:port - currently not used`
Leave the array empty and it will skip connecting to elastic

**Comment by altcnews** [comment]
Hi Dev,
thanks for replying, actually the config is as it is...already empty from the start.
But i commented that line out and recompile and it works.

I will try to explore the bot now.
Thanks & Regards.
