### ISSUE TITLE
im trying to run the program but i get error message 

### ISSUE THREAD

**Issue by Digiguy1** [Ekliptor/WolfBot#16]
node app.js --debug --config=Noop --trader=RealTimeTrader --noUpdate –noBrowser

Error: Cannot find module '@ekliptor/apputils'
    at Function.Module._resolveFilename (module.js:548:15)
    at Function.Module._load (module.js:475:25)
    at Module.require (module.js:597:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/home/hack/crypto/algotrades/WolfBot/app.ts:42:1)
    at Module._compile (module.js:653:30)
    at Object.Module._extensions..js (module.js:664:10)
    at Module.load (module.js:566:32)
    at tryModuleLoad (module.js:506:12)
    at Function.Module._load (module.js:498:3)

**Comment by Ekliptor** [comment]
you have tu compile typescript, meaning run `tsc` in all node_modules of the ekliptor folder that have a `tsconfig.json` file.

**Comment by Digiguy1** [comment]
ok so i run tsc in directory WolfBot/node_modules/@ekliptor/apputils  , 
/WolfBot/node_modules/@ekliptor/bit-models
WolfBot/node_modules/@ekliptor/browserutils$ 
and im still getting errors 

node app.js --debug --config=Noop --trader=RealTimeTrader --noUpdate --noBrowser
2019-04-01 18:20:56 - info: ***DISCOUNT*** Having trouble setting up WolfBot on your local machine? Try the cloud version at https://wolfbot.org with a 30% discount with this code: gitsource7393
Error: Cannot find module './MarketDepth'
    at Function.Module._resolveFilename (module.js:548:15)
    at Function.Module._load (module.js:475:25)
    at Module.require (module.js:597:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/WolfBot/src/Indicators/AbstractIndicator.ts:414:1)
    at Module._compile (module.js:653:30)
    at Object.Module._extensions..js (module.js:664:10)
    at Module.load (module.js:566:32)
    at tryModuleLoad (module.js:506:12)
    at Function.Module._load (module.js:498:3)
    at Module.require (module.js:597:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/WolfBot/src/Strategies/Mixins/TechnicalAnalysis.ts:6:1)
    at Module._compile (module.js:653:30)
    at Object.Module._extensions..js (module.js:664:10)
    at Module.load (module.js:566:32)
    at tryModuleLoad (module.js:506:12)
    at Function.Module._load (module.js:498:3)
    at Module.require (module.js:597:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/WolfBot/src/Strategies/TechnicalStrategy.ts:17:1)
    at Module._compile (module.js:653:30)

**Comment by Ekliptor** [comment]
that import was not available in the open source version. fixed it, please update

**Comment by Digiguy1** [comment]
ok i updated i run tsc on directory 
 directory WolfBot/node_modules/@ekliptor/apputils ,
/WolfBot/node_modules/@ekliptor/bit-models
WolfBot/node_modules/@ekliptor/browserutils
and im still getting errors

node app.js --debug --config=Noop --trader=RealTimeTrader --noUpdate --noBrowser
2019-04-02 16:08:25 - info: ***DISCOUNT*** Having trouble setting up WolfBot on your local machine? Try the cloud version at https://wolfbot.org with a 30% discount with this code: gitsource7393
Error: Cannot find module '../configLocal'
    at Function.Module._resolveFilename (module.js:548:15)
    at Function.Module._load (module.js:475:25)
    at Module.require (module.js:597:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/crypto/algotrades/WolfBot/src/LoginController.ts:12:1)
    at Module._compile (module.js:653:30)
    at Object.Module._extensions..js (module.js:664:10)
    at Module.load (module.js:566:32)
    at tryModuleLoad (module.js:506:12)
    at Function.Module._load (module.js:498:3)
    at Module.require (module.js:597:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/crypto/algotrades/WolfBot/src/Controller.ts:13:1)
    at Module._compile (module.js:653:30)
    at Object.Module._extensions..js (module.js:664:10)
    at Module.load (module.js:566:32)
    at tryModuleLoad (module.js:506:12)
    at Function.Module._load (module.js:498:3)
    at Module.require (module.js:597:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/crypto/algotrades/WolfBot/app.ts:90:1)
    at Module._compile (module.js:653:30)

**Comment by Ekliptor** [comment]
You have to create a config file as mentioned in the readme: https://github.com/Ekliptor/WolfBot/blob/master/README.md

Since it seems you are new to TypeScript/JavaScript I recommend you take a look at WolfBot cloud: https://wolfbot.org/product/cloud-trading-bot-membership/
There is no installation required, it has more features & strategies and better support.

**Comment by Digiguy1** [comment]
i did ceate a configlocal.ts

**Comment by Digiguy1** [comment]
ok i finally got it to work but getting a message on the browser saying i dont have api keys 

Unauthorized
You are not authorized to access this application. Please contact the administrator for an API-Key.

**Comment by Digiguy1** [comment]
never mind i fix it thank so much for your help im excited about the bot

**Comment by clementpl** [comment]
Hello,
Firstly thanks for sharing this project, your work looks amazing !
I was also working on a trading bot wrote in typescript (https://github.com/clementpl/influx-crypto-trader)
But your one looks like doing everything I was looking for ^^

Anyway, I tried to got everything working today.
But i have a problem, when I go to the web interface I have an error 
     -> Cannot find module '../libs/tv/charting_library.min'
What is this library, where can i find it ? TradingView ?

**Comment by clementpl** [comment]
The full trace
Uncaught Error: Cannot find module '../libs/tv/charting_library.min'
    at webpackMissingModule (Strategies.ts:9)
    at Object../public/js/controllers/Strategies.ts (Strategies.ts:9)
    at __webpack_require__ (bootstrap:19)
    at Object../public/js/index.ts (index.ts:15)
    at __webpack_require__ (bootstrap:19)
    at bootstrap:83
    at bootstrap:83

**Comment by Ekliptor** [comment]
Because of their license I am not allowed to publish the TradingView library on github. When you look at how it's actually included from index.html you will see that it is being served from wolfbot.org

As a side-node, you wouldn't need to compile the browser-side code. It's already compiled and I assume you want to create a strategy - a seperate tsconfig.json in the root dir. Even though what really needs improvements is the UI

**Comment by clementpl** [comment]
OK, that's what I was thinking when I found where to download the library and I saw the licence, I will try to download it later and include my "licensed" version. 
Thank you very much

**Comment by moh7afiz90** [comment]
@Digiguy1 can you please share with us the process of how you made the bot work for you, I have been struggling with it for couple of days now!

**Comment by XL-Reaper** [comment]
You have to call the website with the API Key: index.html?apiKey=xxxxxxxxxx
