### ISSUE TITLE
Example code doesn't work.

### ISSUE THREAD

**Issue by Industrial** [Ekliptor/WolfBot#19]
Hi. Upon running `node app.js --debug --config=Noop --trader=RealTimeTrader --noUpdate --noBrowser` I get:

```
Error: Cannot find module '@ekliptor/apputils'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:655:15)
    at Function.Module._load (internal/modules/cjs/loader.js:580:25)
    at Module.require (internal/modules/cjs/loader.js:711:19)
    at require (internal/modules/cjs/helpers.js:14:16)
    at Object.<anonymous> (/home/tom/Code/Code9/WolfBot/app.ts:42:1)
    at Module._compile (internal/modules/cjs/loader.js:805:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:816:10)
    at Module.load (internal/modules/cjs/loader.js:672:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:612:12)
    at Function.Module._load (internal/modules/cjs/loader.js:604:3)
```

**Comment by Ekliptor** [comment]
you must run `tsc` in all folders of node_mudules/@ekliptor as mentioned in the readme. Or let your IDE do it for you.

**Comment by Industrial** [comment]
IDE? I don't use an IDE.

You should provide:
1) A simple `npm install` should be enough to install all dependencies in a Node.js project. Why doesn't it work like this?
2) Proper tooling. If NPM Install can't solve it for you, add NPM scripts that prepare the installation so that it is usable.
3) End up with a `take this command, run it, presto, program runs` scenario, instead of vague instructions to just run a tool or let the IDE manage it or whatever.

**Comment by Industrial** [comment]
@Ekliptor Can I help, by providing PR's?

**Comment by Ekliptor** [comment]
sure.
WolfBot includes a lot of my other modules (from my projects that are not open source), but it's very well separated from it. So you can easily make PRs for WolfBot to add more features
