### ISSUE TITLE
option --bitmex gives an error

### ISSUE THREAD

**Issue by arnoudb** [Ekliptor/WolfBot#30]
`$node app.js --config=Noop.json --trader=RealTimeTrader --noBrowser --noUpdate --days=30 --debug`

works (in Noop.js i set BitMEX as the exchange)

but 

`$node app.js --config=Noop.json --trader=RealTimeTrader --noBrowser --noUpdate --days=30 --debug --bitmex`  

fails with the next error:
```
Error: Cannot find module './BitmexFix'
Require stack:
- /Users/arnoudbos/Documents/crypto/projects/bots/WolfBot/build/src/Exchanges/BitMEX.js
- /Users/arnoudbos/Documents/crypto/projects/bots/WolfBot/build/src/Exchanges/AbstractExchange.js
- /Users/arnoudbos/Documents/crypto/projects/bots/WolfBot/build/src/ExchangeController.js
- /Users/arnoudbos/Documents/crypto/projects/bots/WolfBot/build/src/Controller.js
- /Users/arnoudbos/Documents/crypto/projects/bots/WolfBot/build/app.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:772:15)
    at Function.Module._load (internal/modules/cjs/loader.js:677:27)
    at Module.require (internal/modules/cjs/loader.js:830:19)
    at require (internal/modules/cjs/helpers.js:68:18)
    at Object.<anonymous> (/Users/arnoudbos/Documents/crypto/projects/bots/WolfBot/src/Exchanges/BitMEX.ts:31:88)
    at Module._compile (internal/modules/cjs/loader.js:936:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:947:10)
    at Module.load (internal/modules/cjs/loader.js:790:32)
    at Function.Module._load (internal/modules/cjs/loader.js:703:12)
    at Module.require (internal/modules/cjs/loader.js:830:19)
    at require (internal/modules/cjs/helpers.js:68:18)
    at Object.<anonymous> (/Users/arnoudbos/Documents/crypto/projects/bots/WolfBot/src/Exchanges/AbstractExchange.ts:922:1)
    at Module._compile (internal/modules/cjs/loader.js:936:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:947:10)
    at Module.load (internal/modules/cjs/loader.js:790:32)
    at Function.Module._load (internal/modules/cjs/loader.js:703:12)
    at Module.require (internal/modules/cjs/loader.js:830:19)
    at require (internal/modules/cjs/helpers.js:68:18)
    at Object.<anonymous> (/Users/arnoudbos/Documents/crypto/projects/bots/WolfBot/src/ExchangeController.ts:5:1)
    at Module._compile (internal/modules/cjs/loader.js:936:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:947:10)
    at Module.load (internal/modules/cjs/loader.js:790:32)
```

**Comment by Ekliptor** [comment]
You can't use the `--bitmex` parameter in the open source version. It's a workaround and improvement I wrote for the cloud version alone because the BitMEX API is sometimes unstable and gets out of sync https://github.com/BitMEX/api-connectors/issues/284
And their support is not really willing to help here...
