### ISSUE TITLE
Error: https://registry.yarnpkg.com/@ekliptor%2freddit-snooper: Not found

### ISSUE THREAD

**Issue by prototypensx** [Ekliptor/WolfBot#6]
Thank you for sharing the project.  
`yarn install` produces the below error
Yarn version:
  1.9.4
Node version:
  10.10.0
Error: https://registry.yarnpkg.com/@ekliptor%2freddit-snooper: Not found
      at Request.params.callback [as _callback] (/usr/lib/node_modules/yarn/lib/cli.js:64202:18)
      at Request.self.callback (/usr/lib/node_modules/yarn/lib/cli.js:137468:22)
      at Request.emit (events.js:182:13)
      at Request.<anonymous> (/usr/lib/node_modules/yarn/lib/cli.js:138440:10)
      at Request.emit (events.js:182:13)
      at IncomingMessage.<anonymous> (/usr/lib/node_modules/yarn/lib/cli.js:138362:12)
      at Object.onceWrapper (events.js:273:13)
      at IncomingMessage.emit (events.js:187:15)
      at endReadableNT (_stream_readable.js:1092:12)
      at process._tickCallback (internal/process/next_tick.js:63:19)

**Comment by Ekliptor** [comment]
Hello.
Thanks for the report.
The `@ekliptor/reddit-snooper` package was set to private (default setting) and I forgot to change it. It is now public.

Please try again `yarn install`

I forked this a few weeks ago after they didn't respond to my pull request. Although technically you don't need this package for trading (only the not yet published social sentiment parts).

Let me know if you have further questions

**Comment by prototypensx** [comment]
Thanks for that. 
`yarn install` went smoothly this time. 
Not sure if it is related but I get the below error 
WolfBot/build$ node app.js --config=Noop --trader=RealTimeTrader --noUpdate --noBrowser
Error: Cannot find module '@ekliptor/apputils'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:581:15)
    at Function.Module._load (internal/modules/cjs/loader.js:507:25)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at Object.<anonymous> (/home/bot/WolfBot/app.ts:39:1)
    at Module._compile (internal/modules/cjs/loader.js:689:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
    at Function.Module._load (internal/modules/cjs/loader.js:530:3)

**Comment by prototypensx** [comment]
It seems that apputils is being downloaded after `yarn install` to /home/folder/Wolfbot/node_modules.

When I execute in /home/folder/Wolfbot#`tsc app.ts>wolfbot.log` the output is 

`app.ts(39,24): error TS2307: Cannot find module '@ekliptor/apputils'`

`app.ts(43,25): error TS2497: Module '"/home/bot/WolfBot/src/utils/Logger"' resolves to a non-module entity and cannot be imported using this construct.`
`src/AI/Brain.ts(1,24): error TS2307: Cannot find module '@ekliptor/apputils'.`
..... some more errors as above
`src/utils/Logger.ts(2,24): error TS2307: Cannot find module '@ekliptor/apputils'.`
`src/utils/helper.ts(1,24): error TS2307: Cannot find module '@ekliptor/apputils'.`
`src/utils/helper.ts(17,9): error TS2554: Expected 1-2 arguments, but got 4.`

`node app.js`  output is 
`Error: Cannot find module '@ekliptor/apputils'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:581:15)
    at Function.Module._load (internal/modules/cjs/loader.js:507:25)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at Object.<anonymous> (/home/bot/WolfBot/app.js:70:13)
    at Module._compile (internal/modules/cjs/loader.js:689:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
    at Function.Module._load (internal/modules/cjs/loader.js:530:3)`

I compiled the code running /Wolfbot/`tsc` and then from the build folder `node app.js --config=Noop --trader=RealTimeTrader --noUpdate --noBrowser`

OS: Ubuntu 16.04 x64

`/home/bot/WolfBot# yarn install`
yarn install v1.9.4
[1/4] Resolving packages...
success Already up-to-date.
Done in 0.82s.

`npm install --global webpack`
/usr/bin/webpack -> /usr/lib/node_modules/webpack/bin/webpack.js
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.4 (node_modules/webpack/node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.4: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})

+ webpack@4.17.2
updated 1 package in 5.525s

`npm install -g typescript`

/usr/bin/tsc -> /usr/lib/node_modules/typescript/bin/tsc
/usr/bin/tsserver -> /usr/lib/node_modules/typescript/bin/tsserver
+ typescript@3.0.3
updated 1 package in 1.336s

`node -v`
v10.10.0

**Comment by Ekliptor** [comment]
I am running `tsc` from within my IDE WebStorm.
Also I am still using TypeScript version 2.8.1 - haven't tested v3 yet, but should work.
But if you run it from command line, try running it in watch mode like this: `tsc --pretty` from the root directory with a `tsconfig.json` file. You shouldn't have to specify a `.ts` file.

apputils should be downloaded into `/home/folder/Wolfbot/node_modules/@ekliptor/apputils`. I am using yarn 1.9.4 too and have no idea why it would download packages into the wrong folder.

Your workaround options are:
- manually moving all @ekliptor packages from package.json into a subfolderm`node_modules/@ekliptor/package-name`
- `tsc --pretty` once in all of those modules folders  that have their own `tsconfig.json` to ensure you get compiled code in a `build` directory within the module dir
- investigate the issue why yarn install doesn't create the `@ekliptor` folder. Does it create the `@types` folder? Try filing a question/bug yarn https://github.com/yarnpkg/yarn/issues

**Comment by Ekliptor** [comment]
I can compile WolfBot with TypeScript 3 too (without changes). Although making use of their new "Project References" features could improve compilation and make it more IDE independent.

**Comment by prototypensx** [comment]
Sorry for not clarifying the exact location earlier. 
`yarn install` is downloading apputils in the correct folder `/home/folder/Wolfbot/node_modules/@ekliptor/apputils`  which does not seem to be an issue anymore and @types folder is present too so I think we can rule out missing dependencies for now.

`tsc ` or `tsc --pretty` returns `Found 3322 errors. Watching for file changes.`  and messages as `views/Trader/trades.js:22:29863 - error TS1109: Expression expected.`

I think this is where it failed, I couldn't find tsconfig.json in any of the modules folders or a build directory in the modules folder either. 

Thanks again.

**Comment by Ekliptor** [comment]
The errors on first build are ok, I get them too. As long as you use the `tsconfig.json` from the root dir (which has `noEmitOnError` disabled, the default) then the code will still be compiled to the `build` dir.
The errors mostly last from the fact that client-side TS code from `public/ `is missing some server-side type declarations which I don't want to ship to the client. Still it's on my ToDo to do some refactoring there.

Running `tsc` in the root (plus all `@ekliptor` modules with a tsconfig.json) must fix your missing apputils error since then there will be a `apputils/build/utils.js` file to load available.

**Comment by Ekliptor** [comment]
closing the issue for now after 3 days without response.
Please also view the updated ReadMe about compilation. If you have further questions please ask again.

**Comment by prototypensx** [comment]
Thank you for the tips, I will try them and let you know soon how it goes.

**Comment by kelvindc** [comment]
I'm having the same problem:
OS: mac

steps:
git clone https://github.com/Ekliptor/WolfBot
yarn install 
(all node_modules are perfectly downloaded and found in root/node_modules/*)

run tsc Found 3322 errors. Watching for file changes
has build/app.js


running node build/app.js result in:
Error: Cannot find module '@ekliptor/apputils'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:581:15)
    at Function.Module._load (internal/modules/cjs/loader.js:507:25)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at Object.<anonymous> (/Users/kel_ada/trade/WolfBot/app.ts:40:1)
    at Module._compile (internal/modules/cjs/loader.js:689:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
    at Function.Module._load (internal/modules/cjs/loader.js:530:3)

going back to root/node_modules/@ekliptor/apputils
there's no build folder or anything with .js build by tsc

in tsc log shows:
src/AI/Brain.ts(1,24): error TS2307: Cannot find module '@ekliptor/apputils'.
src/AI/Brain.ts(12,60): error TS2307: Cannot find module '@ekliptor/bit-models'.


I suppose there might be a problem for tsc to recognize the node_modules when it's exists, but all the tsconfig seems to be ok so it's kind of strange

**Comment by Ekliptor** [comment]
what version of tsc are you using?
please go into /node_modules/@ekliptor/apputils and rune tsc once there

**Comment by kelvindc** [comment]
tried tsc 2.8.2 and also 2.9.2 didn't work.

tsc on /node_modules/@ekliptor/apputils result in Found 21 errors. Watching for file changes:

date.ts:157:29 - error TS2339: Property 'trim' does not exist on type 'Buffer'.
157             stdout = stdout.trim();
                                ~~~
date.ts:160:49 - error TS2345: Argument of type 'Buffer' is not assignable to parameter of type 'string'.
160             resolve(parseElapsedUnixProcessDate(stdout))
                                                    ~~~~~~



tsc on /node_modules/@ekliptor/bit-models result in Found 2 errors. Watching for file changes:

models/Trade.ts:193:9 - error TS2322: Type '[number, number]' is not assignable to type 'CurrencyPair'.
  Property 'from' is missing in type '[number, number]'.

193         trade.currencyPair = trade.currencyPair.toNr();
            ~~~~~~~~~~~~~~~~~~


models/TradeHistory.ts:45:5 - error TS2322: Type '[number, number]' is not assignable to type 'CurrencyPair'.

45     insertHistory.currencyPair = pairNr;
       ~~~~~~~~~~~~~~~~~~~~~~~~~~


[5:46:26 AM] Found 2 errors. Watching for file changes.

**Comment by kelvindc** [comment]
node -v
v10.11.0

yarn -v
1.10.1

mongo --version
MongoDB shell version v4.0.2
git version: fc1573ba18aee42f97a3bb13b67af7d837826b47
allocator: system
modules: none
build environment:
    distarch: x86_64
    target_arch: x86_64

tsc -v
Version 2.9.2

uname -a
Darwin 18.0.0 Darwin Kernel Version 18.0.0: Wed Aug 22 20:13:40 PDT 2018; root:xnu-4903.201.2~1/RELEASE_X86_64 x86_64

**Comment by Ekliptor** [comment]
some errors are ok as mentioned in the Readme. does the bot start or give you a nodejs error too?

**Comment by kelvindc** [comment]
it doesn't start. I think the errors cause apputils not being able to build by tsc

on osx apputils didn't build:
Error: Cannot find module '@ekliptor/apputils'
at Function.Module._resolveFilename (internal/modules/cjs/loader.js:581:15)

tried on osx, ubuntu, and even on docker with fresh os still get the same above error.

on ubuntu gets a different error(going back to @ekliptor/apputils still don't see any js get built ):
Error: Cannot find module './Crawler/AbstractCrawler'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:581:15)

on docker alphine I still haven't figured out a way to log the output but it failed too

**Comment by Ekliptor** [comment]
> Error: Cannot find module './Crawler/AbstractCrawler'
That error means you didn't use the --noBrowser parameter as mentioned in the readme.

Other than that. Please ensure every of my modules has build output, that means: node_modules/@ekliptor/xxx/build/ contains some javascript files. Otherwise run tsc in the root folder of that module. Then nodejs will start.

**Comment by ynzheng** [comment]
I'm having the same problem:
OS: Debian 9

**ENV：**
$ node -v
v10.11.0

r$ mongo --version
MongoDB shell version v4.0.2
git version: fc1573ba18aee42f97a3bb13b67af7d837826b47
OpenSSL version: OpenSSL 1.1.0f  25 May 2017
allocator: tcmalloc
modules: none
build environment:
    distmod: debian92
    distarch: x86_64
    target_arch: x86_64

$  tsc -v
Version 3.1.1

$  yarn -v
1.10.1

$ webpack --version
4.20.2

$ cat /etc/debian_version
9.5

$ uname -a
Linux hostdoc 4.9.0-8-amd64 #1 SMP Debian 4.9.110-3+deb9u4 (2018-08-21) x86_64 GNU/Linux

**Steps:**
rm -rf WolfBot/
git clone https://github.com/Ekliptor/WolfBot
cd WolfBot
yarn install

![image](https://user-images.githubusercontent.com/107111/46481681-7ca06900-c826-11e8-9eb8-c429e2d0d709.png)

cp configLocal-sample.ts configLocal.ts
tsc

![image](https://user-images.githubusercontent.com/107111/46482360-0a308880-c828-11e8-9076-1538c01fedb2.png)

cd node_modules/@ekliptor/apputils 
tsc

![image](https://user-images.githubusercontent.com/107111/46482591-7c08d200-c828-11e8-87ae-d68fc9045ae0.png)
![image](https://user-images.githubusercontent.com/107111/46482678-a5296280-c828-11e8-93b0-90f9568f4398.png)
![image](https://user-images.githubusercontent.com/107111/46482740-c0946d80-c828-11e8-8a5a-549c8d48dd8c.png)

cd node_modules/@ekliptor/browserutils 
tsc

[10:57:28 PM] Starting compilation in watch mode...
[10:57:31 PM] Found 0 errors. Watching for file changes.

cd node_modules/@ekliptor/bit-models 
tsc

![image](https://user-images.githubusercontent.com/107111/46482935-1f59e700-c829-11e8-8559-7033458c8a4f.png)

cd build/
node app.js --debug --config=Noop --trader=RealTimeTrader --noUpdate –noBrowser

![image](https://user-images.githubusercontent.com/107111/46483011-4a443b00-c829-11e8-8fc3-6610569d668c.png)

**Comment by ynzheng** [comment]
sorry，the command should be

node app.js --debug --config=Noop --trader=RealTimeTrader --noUpdate --noBrowser

2018-10-04 23:35:24 - error: No local config file found. Please ensure the file /home/yn/github.com/ekliptor/WolfBot/build/configLocal.js exists.
You can edit and copy it from configLocal-sample.ts

So ,I do

cp configLocal-sample.js configLocal.js

almost works

**Comment by ynzheng** [comment]
I got these error and this warn: TypeError: Cannot set property 'isAdminInstance' of null

2018-10-05 00:02:09 - info: Server is listening on http://hostdoc:8331/index.html?apiKey=JFSDFHl340udfnsf23SF234
2018-10-05 00:02:09 - info: Server is listening on https://hostdoc:8332/index.html?apiKey=JFSDFHl340udfnsf23SF234
2018-10-05 00:02:09 - verbose: Ta-Lib successfully loaded. Ta-Lib Version 1.0.2 ready
2018-10-05 00:02:09 - info: minified all resources
2018-10-05 00:02:09 - info: Connected to MongoDB
2018-10-05 00:02:09 - error: failed to load module: /home/yn/github.com/ekliptor/WolfBot/build/src/Notifications/Pushover {"message":"Pushover appToken must be set to send Pushover notifications","stack":"Error: Pushover appToken must be set to send Pushover notifications\n    at new Pushover (/home/yn/github.com/ekliptor/WolfBot/src/Notifications/Pushover.ts:13:19)\n    at Function.loadModule (/home/yn/github.com/ekliptor/WolfBot/src/Notifications/AbstractNotification.ts:87:28)\n    at Function.getInstance (/home/yn/github.com/ekliptor/WolfBot/src/Notifications/AbstractNotification.ts:36:75)\n    at new InstanceChecker (/home/yn/github.com/ekliptor/WolfBot/src/InstanceChecker.ts:33:46)\n    at Controller.doProcess (/home/yn/github.com/ekliptor/WolfBot/src/Controller.ts:248:36)\n    at loadServerConfig (/home/yn/github.com/ekliptor/WolfBot/src/Controller.ts:230:18)\n    at bit_models_1.serverConfig.loadServerConfig (/home/yn/github.com/ekliptor/WolfBot/src/Controller.ts:341:27)\n    at Timeout.setTimeout (/home/yn/github.com/ekliptor/WolfBot/node_modules/@ekliptor/bit-models/models/serverConfig.ts:379:15)\n    at ontimeout (timers.js:425:11)\n    at tryOnTimeout (timers.js:289:5)\n    at listOnTimeout (timers.js:252:5)\n    at Timer.processTimers (timers.js:212:10)"}
2018-10-05 00:02:09 - error: Loading admin notification class Pushover failed. Loading fallback
2018-10-05 00:02:09 - error: failed to load module: /home/yn/github.com/ekliptor/WolfBot/build/src/Notifications/Pushover {"message":"Pushover appToken must be set to send Pushover notifications","stack":"Error: Pushover appToken must be set to send Pushover notifications\n    at new Pushover (/home/yn/github.com/ekliptor/WolfBot/src/Notifications/Pushover.ts:13:19)\n    at Function.loadModule (/home/yn/github.com/ekliptor/WolfBot/src/Notifications/AbstractNotification.ts:87:28)\n    at Function.getInstance (/home/yn/github.com/ekliptor/WolfBot/src/Notifications/AbstractNotification.ts:39:79)\n    at new InstanceChecker (/home/yn/github.com/ekliptor/WolfBot/src/InstanceChecker.ts:33:46)\n    at Controller.doProcess (/home/yn/github.com/ekliptor/WolfBot/src/Controller.ts:248:36)\n    at loadServerConfig (/home/yn/github.com/ekliptor/WolfBot/src/Controller.ts:230:18)\n    at bit_models_1.serverConfig.loadServerConfig (/home/yn/github.com/ekliptor/WolfBot/src/Controller.ts:341:27)\n    at Timeout.setTimeout (/home/yn/github.com/ekliptor/WolfBot/node_modules/@ekliptor/bit-models/models/serverConfig.ts:379:15)\n    at ontimeout (timers.js:425:11)\n    at tryOnTimeout (timers.js:289:5)\n    at listOnTimeout (timers.js:252:5)\n    at Timer.processTimers (timers.js:212:10)"}
2018-10-05 00:02:09 - warn: Uncaught Exception
2018-10-05 00:02:09 - warn:  {"message":"Cannot set property 'isAdminInstance' of null","stack":"TypeError: Cannot set property 'isAdminInstance' of null\n    at Function.getInstance (/home/yn/github.com/ekliptor/WolfBot/src/Notifications/AbstractNotification.ts:42:63)\n    at new InstanceChecker (/home/yn/github.com/ekliptor/WolfBot/src/InstanceChecker.ts:33:46)\n    at Controller.doProcess (/home/yn/github.com/ekliptor/WolfBot/src/Controller.ts:248:36)\n
  at loadServerConfig (/home/yn/github.com/ekliptor/WolfBot/src/Controller.ts:230:18)\n    at bit_models_1.serverConfig.loadServerConfig (/home/yn/github.com/ekliptor/WolfBot/src/Controller.ts:341:27)\n    at Timeout.setTimeout (/home/yn/github.com/ekliptor/WolfBot/node_modules/@ekliptor/bit-models/models/serverConfig.ts:379:15)\n    at ontimeout (timers.js:425:11)\n    at tryOnTimeout (timers.js:289:5)\n    at listOnTimeout (timers.js:252:5)\n    at Timer.processTimers (timers.js:212:10)"}
2018-10-05 00:02:09 - warn: TypeError: Cannot set property 'isAdminInstance' of null
    at Function.getInstance (/home/yn/github.com/ekliptor/WolfBot/src/Notifications/AbstractNotification.ts:42:63)
    at new InstanceChecker (/home/yn/github.com/ekliptor/WolfBot/src/InstanceChecker.ts:33:46)
    at Controller.doProcess (/home/yn/github.com/ekliptor/WolfBot/src/Controller.ts:248:36)
    at loadServerConfig (/home/yn/github.com/ekliptor/WolfBot/src/Controller.ts:230:18)
    at bit_models_1.serverConfig.loadServerConfig (/home/yn/github.com/ekliptor/WolfBot/src/Controller.ts:341:27)
    at Timeout.setTimeout (/home/yn/github.com/ekliptor/WolfBot/node_modules/@ekliptor/bit-models/models/serverConfig.ts:379:15)
    at ontimeout (timers.js:425:11)
    at tryOnTimeout (timers.js:289:5)
    at listOnTimeout (timers.js:252:5)
    at Timer.processTimers (timers.js:212:10)

**Comment by kelvindc** [comment]
updates:
I was able to get it working on ubuntu but not on osx, here are the steps to make it work on ubuntu:

git clone https://github.com/Ekliptor/WolfBot
cd WolfBot
yarn install

____ begin of missing actions____
cp ~/your_folder_of/configLocal.ts ./

pushover setting is required in configLocal.ts or the script will fail to run
(can edit src/Notifications/Pushover.ts to get around this error)

my own preference for non IDE build: edit all tsconfig.json and remove "watch": true, to enable watch function simply use tsc -w
____ end of missing actions____

tsc

cd build

node app.js --debug --config=Noop --trader=RealTimeTrader --noUpdate –noBrowser

**Comment by Ekliptor** [comment]
@ynzheng: the error means you have enabled Pushover notifications without entering API keys for their service. Disable it. I also just published a sample config explicitly setting it to NoNotificationService.

@kelvindc: No idea how it can work on one machine and not on the other since it doesn't use anything but nodejs.

**Comment by ynzheng** [comment]
> @ynzheng: the error means you have enabled Pushover notifications without entering API keys for their service. Disable it. I also just published a sample config explicitly setting it to NoNotificationService.
> 
I rebuilded again from the very begining..
same error,even with NoNotificationService config there

then I set the Pushover appToken&receiver that I got from Pushover   ...

error`s gone,but only some warning as following
     
2018-10-06 02:08:07 - info: Server is listening on http://hostdoc:8331/index.html?apiKey=JFSDFHl340udfnsf23SF234
2018-10-06 02:08:07 - info: Server is listening on https://hostdoc:8332/index.html?apiKey=JFSDFHl340udfnsf23SF234
2018-10-06 02:08:07 - verbose: Ta-Lib successfully loaded. Ta-Lib Version 1.0.2 ready
2018-10-06 02:08:07 - info: minified all resources
2018-10-06 02:08:07 - info: Connected to MongoDB
2018-10-06 02:08:07 - warn: Unhandled promise rejection {"message":"Cannot read property 'getExchangeLabel' of undefined","stack":"TypeError: Cannot read property 'getExchangeLabel' of undefined\n    at json.data.forEach (/home/yn/github.com/ekliptor/WolfBot/src/TradeAdvisor.ts:467:131)\n    at Array.forEach (<anonymous>)\n    at TradeAdvisor.loadConfig (/home/yn/github.com/ekliptor/WolfBot/src/TradeAdvisor.ts:443:19)\n    at TradeAdvisor.checkRestoreConfig.then (/home/yn/github.com/ekliptor/WolfBot/src/TradeAdvisor.ts:213:18)"}
2018-10-06 02:08:07 - warn: Unhandled Rejection
2018-10-06 02:08:07 - warn:  {"message":"Cannot read property 'getExchangeLabel' of undefined","stack":"TypeError: Cannot read property 'getExchangeLabel' of undefined\n    at json.data.forEach (/home/yn/github.com/ekliptor/WolfBot/src/TradeAdvisor.ts:467:131)\n    at Array.forEach (<anonymous>)\n    at TradeAdvisor.loadConfig (/home/yn/github.com/ekliptor/WolfBot/src/TradeAdvisor.ts:443:19)\n    at TradeAdvisor.checkRestoreConfig.then (/home/yn/github.com/ekliptor/WolfBot/src/TradeAdvisor.ts:213:18)"}
2018-10-06 02:08:07 - warn: TypeError: Cannot read property 'getExchangeLabel' of undefined
    at json.data.forEach (/home/yn/github.com/ekliptor/WolfBot/src/TradeAdvisor.ts:467:131)
    at Array.forEach (<anonymous>)
    at TradeAdvisor.loadConfig (/home/yn/github.com/ekliptor/WolfBot/src/TradeAdvisor.ts:443:19)
    at TradeAdvisor.checkRestoreConfig.then (/home/yn/github.com/ekliptor/WolfBot/src/TradeAdvisor.ts:213:18)

**Comment by fractalawareness** [comment]
This bot is not so easy to launch.
I've created docker-compose file with mongo service, created script to run **tsc** on each ekliptor dependencies folder with tsconfig inside, but now facing errors about missing files (that are really missing from the repo). Where do I get these?

```
src/Controller.ts:29:34 - error TS2307: Cannot find module './Social/Crawler/Telegram'.
29 import {RawTelegramMessage} from "./Social/Crawler/Telegram";
-----------
src/WebSocket/TradingViewData.ts:21:30 - error TS2307: Cannot find module '../../public/js/libs/tv                                                             /charting_library.min'.
21 import * as TradingView from "../../public/js/libs/tv/charting_library.min"
```
