### ISSUE TITLE
Installation Error (MongoDB)

### ISSUE THREAD

**Issue by exp-cryp** [Ekliptor/WolfBot#70]
Hi - trying to install but keep getting the following error:

`
WolfBot/build$ node app.js --debug --config=Noop --trader=RealTimeTrader --noUpdate --noBrowser
2020-06-19 14:18:30 - info: ***DISCOUNT*** Having trouble setting up WolfBot on your local machine? Try the cloud version at https://wolfbot.org with a 30% discount with this code: gitsource7393
2020-06-19 14:18:31 - verbose: Ta-Lib successfully loaded. Ta-Lib Version 1.1.2 ready
2020-06-19 14:18:31 - error: Error connecting to MongoDB {"message":"failed to connect to server [localhost:2007] on first connect [Error: connect ECONNREFUSED 127.0.0.1:2007\n    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1141:16) {\n  name: 'MongoError'\n}]","name":"MongoError","stack":"MongoError: failed to connect to server [localhost:2007] on first connect [Error: connect ECONNREFUSED 127.0.0.1:2007\n    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1141:16) {\n  name: 'MongoError'\n}]\n    at Pool.<anonymous> (/home/me/WolfBot/node_modules/mongodb-core/lib/topologies/server.js:336:35)\n    at Pool.emit (events.js:315:20)\n    at Connection.<anonymous> (/home/me/WolfBot/node_modules/mongodb-core/lib/connection/pool.js:280:12)\n    at Object.onceWrapper (events.js:422:26)\n    at Connection.emit (events.js:315:20)\n    at Socket.<anonymous> (/home/me/WolfBot/node_modules/mongodb-core/lib/connection/connection.js:189:49)\n    at Object.onceWrapper (events.js:422:26)\n    at Socket.emit (events.js:315:20)\n    at emitErrorNT (internal/streams/destroy.js:92:8)\n    at emitErrorAndCloseNT (internal/streams/destroy.js:60:3)\n    at processTicksAndRejections (internal/process/task_queues.js:84:21)"}
2020-06-19 14:18:31 - info: Main process exited with code 1
`
Can you help please?

Thank you in advance.

**Comment by exp-cryp** [comment]
Please ignore - had an issue with my mongodb configuration.

**Comment by exp-cryp** [comment]
Apologies for closing and reopening. I'm still getting the same error when I reinstalled everything again.

**Comment by exp-cryp** [comment]
Apologies for closing and reopening. I'm still getting the same error when I reinstalled everything again.

**Comment by exp-cryp** [comment]
Solved the issue so closing this. Looking forward to testing. Thanks
