### ISSUE TITLE
Error Backtesting

### ISSUE THREAD

**Issue by jordanlanch** [Ekliptor/WolfBot#83]
```
2020-09-24 05:33:53 - warn: Error setting process active TypeError: Update document requires atomic operators
TypeError: Update document requires atomic operators
    at new UpdateOneOperation (/home/jordanlanch/WolfBot/node_modules/mongodb/lib/operations/update_one.js:12:13)
    at Collection.updateOne (/home/jordanlanch/WolfBot/node_modules/mongodb/lib/collection.js:758:5)
    at collection.findOne.then (/home/jordanlanch/WolfBot/node_modules/@ekliptor/bit-models/models/Process.ts:74:20)
    at process._tickCallback (internal/process/next_tick.js:68:7)
2020-09-24 05:33:54 - verbose: Updating portfolio of 1 exchanges in RealTimeTrader
2020-09-24 05:33:55 - verbose: Synced Bitfinex USD_BTC portfolio: 1.8e-7 coins, 0 margin amount
2020-09-24 05:33:55 - verbose: Synced Bitfinex USD_ETH portfolio: 0 coins, 0 margin amount
2020-09-24 05:33:56 - warn: Error setting process active TypeError: Update document requires atomic operators
TypeError: Update document requires atomic operators
    at new UpdateOneOperation (/home/jordanlanch/WolfBot/node_modules/mongodb/lib/operations/update_one.js:12:13)
    at Collection.updateOne (/home/jordanlanch/WolfBot/node_modules/mongodb/lib/collection.js:758:5)
    at collection.findOne.then (/home/jordanlanch/WolfBot/node_modules/@ekliptor/bit-models/models/Process.ts:74:20)
    at process._tickCallback (internal/process/next_tick.js:68:7)
2020-09-24 05:33:57 - verbose: Checked Bitfinex margin collateral (for possible margin call): 1
2020-09-24 05:34:01 - warn: Error setting process active TypeError: Update document requires atomic operators
TypeError: Update document requires atomic operators
    at new UpdateOneOperation (/home/jordanlanch/WolfBot/node_modules/mongodb/lib/operations/update_one.js:12:13)
    at Collection.updateOne (/home/jordanlanch/WolfBot/node_modules/mongodb/lib/collection.js:758:5)
    at collection.findOne.then (/home/jordanlanch/WolfBot/node_modules/@ekliptor/bit-models/models/Process.ts:74:20)
    at process._tickCallback (internal/process/next_tick.js:68:7)
2020-09-24 05:34:01 - verbose: Fetched ticker of Bitfinex
2020-09-24 05:34:04 - verbose: 1min BITFINEX candle USD_BTC at 2020-09-24 05:33:00: high 10318.36815700, low 10318.36815700, close 10318.36815700, volume 0.10000000, trades 1
2020-09-24 05:34:04 - warn: Error setting process active TypeError: Update document requires atomic operators
TypeError: Update document requires atomic operators
    at new UpdateOneOperation (/home/jordanlanch/WolfBot/node_modules/mongodb/lib/operations/update_one.js:12:13)
    at Collection.updateOne (/home/jordanlanch/WolfBot/node_modules/mongodb/lib/collection.js:758:5)
    at collection.findOne.then (/home/jordanlanch/WolfBot/node_modules/@ekliptor/bit-models/models/Process.ts:74:20)
    at process._tickCallback (internal/process/next_tick.js:68:7)
2020-09-24 05:34:09 - warn: Error setting process active TypeError: Update document requires atomic operators
TypeError: Update document requires atomic operators
    at new UpdateOneOperation (/home/jordanlanch/WolfBot/node_modules/mongodb/lib/operations/update_one.js:12:13)
    at Collection.updateOne (/home/jordanlanch/WolfBot/node_modules/mongodb/lib/collection.js:758:5)
    at collection.findOne.then (/home/jordanlanch/WolfBot/node_modules/@ekliptor/bit-models/models/Process.ts:74:20)
    at process._tickCallback (internal/process/next_tick.js:68:7)
2020-09-24 05:34:11 - verbose: 1min BITFINEX candle USD_ETH at 2020-09-24 05:33:00: high 326.02000000, low 325.87000000, close 326.02000000, volume 47.11900000, trades 7
2020-09-24 05:34:14 - warn: Error setting process active TypeError: Update document requires atomic operators
TypeError: Update document requires atomic operators
    at new UpdateOneOperation (/home/jordanlanch/WolfBot/node_modules/mongodb/lib/operations/update_one.js:12:13)
    at Collection.updateOne (/home/jordanlanch/WolfBot/node_modules/mongodb/lib/collection.js:758:5)
    at collection.findOne.then (/home/jordanlanch/WolfBot/node_modules/@ekliptor/bit-models/models/Process.ts:74:20)
    at process._tickCallback (internal/process/next_tick.js:68:7)
2020-09-24 05:34:18 - warn: Error setting process active TypeError: Update document requires atomic operators
TypeError: Update document requires atomic operators
    at new UpdateOneOperation (/home/jordanlanch/WolfBot/node_modules/mongodb/lib/operations/update_one.js:12:13)
    at Collection.updateOne (/home/jordanlanch/WolfBot/node_modules/mongodb/lib/collection.js:758:5)
    at collection.findOne.then (/home/jordanlanch/WolfBot/node_modules/@ekliptor/bit-models/models/Process.ts:74:20)
    at process._tickCallback (internal/process/next_tick.js:68:7)
2020-09-24 05:34:21 - warn: Error setting process active TypeError: Update document requires atomic operators
TypeError: Update document requires atomic operators
    at new UpdateOneOperation (/home/jordanlanch/WolfBot/node_modules/mongodb/lib/operations/update_one.js:12:13)
    at Collection.updateOne (/home/jordanlanch/WolfBot/node_modules/mongodb/lib/collection.js:758:5)
    at collection.findOne.then (/home/jordanlanch/WolfBot/node_modules/@ekliptor/bit-models/models/Process.ts:74:20)
    at process._tickCallback (internal/process/next_tick.js:68:7)
2020-09-24 05:34:26 - warn: Error setting process active TypeError: Update document requires atomic operators
TypeError: Update document requires atomic operators
    at new UpdateOneOperation (/home/jordanlanch/WolfBot/node_modules/mongodb/lib/operations/update_one.js:12:13)
    at Collection.updateOne (/home/jordanlanch/WolfBot/node_modules/mongodb/lib/collection.js:758:5)
    at collection.findOne.then (/home/jordanlanch/WolfBot/node_modules/@ekliptor/bit-models/models/Process.ts:74:20)
    at process._tickCallback (internal/process/next_tick.js:68:7)
2020-09-24 05:34:27 - warn: Error setting process active TypeError: Update document requires atomic operators
TypeError: Update document requires atomic operators
    at new UpdateOneOperation (/home/jordanlanch/WolfBot/node_modules/mongodb/lib/operations/update_one.js:12:13)
    at Collection.updateOne (/home/jordanlanch/WolfBot/node_modules/mongodb/lib/collection.js:758:5)
    at collection.findOne.then (/home/jordanlanch/WolfBot/node_modules/@ekliptor/bit-models/models/Process.ts:74:20)
    at process._tickCallback (internal/process/next_tick.js:68:7)
2020-09-24 05:34:29 - warn: Error setting process active TypeError: Update document requires atomic operators
TypeError: Update document requires atomic operators
    at new UpdateOneOperation (/home/jordanlanch/WolfBot/node_modules/mongodb/lib/operations/update_one.js:12:13)
    at Collection.updateOne (/home/jordanlanch/WolfBot/node_modules/mongodb/lib/collection.js:758:5)
    at collection.findOne.then (/home/jordanlanch/WolfBot/node_modules/@ekliptor/bit-models/models/Process.ts:74:20)
    at process._tickCallback (internal/process/next_tick.js:68:7)
2020-09-24 05:34:31 - warn: Error setting process active TypeError: Update document requires atomic operators
TypeError: Update document requires atomic operators
    at new UpdateOneOperation (/home/jordanlanch/WolfBot/node_modules/mongodb/lib/operations/update_one.js:12:13)
    at Collection.updateOne (/home/jordanlanch/WolfBot/node_modules/mongodb/lib/collection.js:758:5)
    at collection.findOne.then (/home/jordanlanch/WolfBot/node_modules/@ekliptor/bit-models/models/Process.ts:74:20)
    at process._tickCallback (internal/process/next_tick.js:68:7)
2020-09-24 05:34:32 - warn: Error setting process active TypeError: Update document requires atomic operators
TypeError: Update document requires atomic operators
    at new UpdateOneOperation (/home/jordanlanch/WolfBot/node_modules/mongodb/lib/operations/update_one.js:12:13)
    at Collection.updateOne (/home/jordanlanch/WolfBot/node_modules/mongodb/lib/collection.js:758:5)
    at collection.findOne.then (/home/jordanlanch/WolfBot/node_modules/@ekliptor/bit-models/models/Process.ts:74:20)
    at process._tickCallback (internal/process/next_tick.js:68:7)
2020-09-24 05:34:36 - warn: Error setting process active TypeError: Update document requires atomic operators
TypeError: Update document requires atomic operators
    at new UpdateOneOperation (/home/jordanlanch/WolfBot/node_modules/mongodb/lib/operations/update_one.js:12:13)
    at Collection.updateOne (/home/jordanlanch/WolfBot/node_modules/mongodb/lib/collection.js:758:5)
    at collection.findOne.then (/home/jordanlanch/WolfBot/node_modules/@ekliptor/bit-models/models/Process.ts:74:20)
    at process._tickCallback (internal/process/next_tick.js:68:7)
2020-09-24 05:34:41 - warn: Error setting process active TypeError: Update document requires atomic operators
TypeError: Update document requires atomic operators
    at new UpdateOneOperation (/home/jordanlanch/WolfBot/node_modules/mongodb/lib/operations/update_one.js:12:13)
    at Collection.updateOne (/home/jordanlanch/WolfBot/node_modules/mongodb/lib/collection.js:758:5)
    at collection.findOne.then (/home/jordanlanch/WolfBot/node_modules/@ekliptor/bit-models/models/Process.ts:74:20)
    at process._tickCallback (internal/process/next_tick.js:68:7)
2020-09-24 05:34:43 - warn: Error setting process active TypeError: Update document requires atomic operators
TypeError: Update document requires atomic operators
    at new UpdateOneOperation (/home/jordanlanch/WolfBot/node_modules/mongodb/lib/operations/update_one.js:12:13)
    at Collection.updateOne (/home/jordanlanch/WolfBot/node_modules/mongodb/lib/collection.js:758:5)
    at collection.findOne.then (/home/jordanlanch/WolfBot/node_modules/@ekliptor/bit-models/models/Process.ts:74:20)
    at process._tickCallback (internal/process/next_tick.js:68:7)
2020-09-24 05:34:48 - warn: Error setting process active TypeError: Update document requires atomic operators
TypeError: Update document requires atomic operators
    at new UpdateOneOperation (/home/jordanlanch/WolfBot/node_modules/mongodb/lib/operations/update_one.js:12:13)
    at Collection.updateOne (/home/jordanlanch/WolfBot/node_modules/mongodb/lib/collection.js:758:5)
    at collection.findOne.then (/home/jordanlanch/WolfBot/node_modules/@ekliptor/bit-models/models/Process.ts:74:20)
    at process._tickCallback (internal/process/next_tick.js:68:7)
2020-09-24 05:34:49 - warn: Error setting process active TypeError: Update document requires atomic operators
TypeError: Update document requires atomic operators
    at new UpdateOneOperation (/home/jordanlanch/WolfBot/node_modules/mongodb/lib/operations/update_one.js:12:13)
    at Collection.updateOne (/home/jordanlanch/WolfBot/node_modules/mongodb/lib/collection.js:758:5)
    at collection.findOne.then (/home/jordanlanch/WolfBot/node_modules/@ekliptor/bit-models/models/Process.ts:74:20)
    at process._tickCallback (internal/process/next_tick.js:68:7)
2020-09-24 05:34:50 - warn: Error setting process active TypeError: Update document requires atomic operators
TypeError: Update document requires atomic operators
    at new UpdateOneOperation (/home/jordanlanch/WolfBot/node_modules/mongodb/lib/operations/update_one.js:12:13)
    at Collection.updateOne (/home/jordanlanch/WolfBot/node_modules/mongodb/lib/collection.js:758:5)
    at collection.findOne.then (/home/jordanlanch/WolfBot/node_modules/@ekliptor/bit-models/models/Process.ts:74:20)
    at process._tickCallback (internal/process/next_tick.js:68:7)
2020-09-24 05:34:54 - warn: Error setting process active TypeError: Update document requires atomic operators
TypeError: Update document requires atomic operators
    at new UpdateOneOperation (/home/jordanlanch/WolfBot/node_modules/mongodb/lib/operations/update_one.js:12:13)
    at Collection.updateOne (/home/jordanlanch/WolfBot/node_modules/mongodb/lib/collection.js:758:5)
    at collection.findOne.then (/home/jordanlanch/WolfBot/node_modules/@ekliptor/bit-models/models/Process.ts:74:20)
    at process._tickCallback (internal/process/next_tick.js:68:7)
2020-09-24 05:34:57 - warn: Error setting process active TypeError: Update document requires atomic operators
TypeError: Update document requires atomic operators
    at new UpdateOneOperation (/home/jordanlanch/WolfBot/node_modules/mongodb/lib/operations/update_one.js:12:13)
    at Collection.updateOne (/home/jordanlanch/WolfBot/node_modules/mongodb/lib/collection.js:758:5)
    at collection.findOne.then (/home/jordanlanch/WolfBot/node_modules/@ekliptor/bit-models/models/Process.ts:74:20)
    at process._tickCallback (internal/process/next_tick.js:68:7)
2020-09-24 05:35:02 - warn: Error setting process active TypeError: Update document requires atomic operators
TypeError: Update document requires atomic operators
    at new UpdateOneOperation (/home/jordanlanch/WolfBot/node_modules/mongodb/lib/operations/update_one.js:12:13)
    at Collection.updateOne (/home/jordanlanch/WolfBot/node_modules/mongodb/lib/collection.js:758:5)
    at collection.findOne.then (/home/jordanlanch/WolfBot/node_modules/@ekliptor/bit-models/models/Process.ts:74:20)
    at process._tickCallback (internal/process/next_tick.js:68:7)
2020-09-24 05:35:02 - verbose: Fetched ticker of Bitfinex
2020-09-24 05:35:05 - warn: Error setting process active TypeError: Update document requires atomic operators
TypeError: Update document requires atomic operators
    at new UpdateOneOperation (/home/jordanlanch/WolfBot/node_modules/mongodb/lib/operations/update_one.js:12:13)
    at Collection.updateOne (/home/jordanlanch/WolfBot/node_modules/mongodb/lib/collection.js:758:5)
    at collection.findOne.then (/home/jordanlanch/WolfBot/node_modules/@ekliptor/bit-models/models/Process.ts:74:20)
    at process._tickCallback (internal/process/next_tick.js:68:7)
2020-09-24 05:35:09 - warn: Error setting process active TypeError: Update document requires atomic operators
TypeError: Update document requires atomic operators
    at new UpdateOneOperation (/home/jordanlanch/WolfBot/node_modules/mongodb/lib/operations/update_one.js:12:13)
    at Collection.updateOne (/home/jordanlanch/WolfBot/node_modules/mongodb/lib/collection.js:758:5)
    at collection.findOne.then (/home/jordanlanch/WolfBot/node_modules/@ekliptor/bit-models/models/Process.ts:74:20)
    at process._tickCallback (internal/process/next_tick.js:68:7)
2020-09-24 05:35:10 - verbose: 1min BITFINEX candle USD_BTC at 2020-09-24 05:34:00: high 10319.00000000, low 10319.00000000, close 10319.00000000, volume 0.44487680, trades 5
2020-09-24 05:35:10 - verbose: 1min BITFINEX candle USD_ETH at 2020-09-24 05:34:00: high 325.92972488, low 325.90051502, close 325.90051502, volume 56.14889520, trades 8
2020-09-24 05:35:11 - warn: Error setting process active TypeError: Update document requires atomic operators
TypeError: Update document requires atomic operators
    at new UpdateOneOperation (/home/jordanlanch/WolfBot/node_modules/mongodb/lib/operations/update_one.js:12:13)
    at Collection.updateOne (/home/jordanlanch/WolfBot/node_modules/mongodb/lib/collection.js:758:5)
    at collection.findOne.then (/home/jordanlanch/WolfBot/node_modules/@ekliptor/bit-models/models/Process.ts:74:20)
    at process._tickCallback (internal/process/next_tick.js:68:7)
2020-09-24 05:35:14 - warn: Error setting process active TypeError: Update document requires atomic operators
TypeError: Update document requires atomic operators
    at new UpdateOneOperation (/home/jordanlanch/WolfBot/node_modules/mongodb/lib/operations/update_one.js:12:13)
    at Collection.updateOne (/home/jordanlanch/WolfBot/node_modules/mongodb/lib/collection.js:758:5)
    at collection.findOne.then (/home/jordanlanch/WolfBot/node_modules/@ekliptor/bit-models/models/Process.ts:74:20)
    at process._tickCallback (internal/process/next_tick.js:68:7)
2020-09-24 05:35:17 - warn: Error setting process active TypeError: Update document requires atomic operators
TypeError: Update document requires atomic operators
    at new UpdateOneOperation (/home/jordanlanch/WolfBot/node_modules/mongodb/lib/operations/update_one.js:12:13)
    at Collection.updateOne (/home/jordanlanch/WolfBot/node_modules/mongodb/lib/collection.js:758:5)
    at collection.findOne.then (/home/jordanlanch/WolfBot/node_modules/@ekliptor/bit-models/models/Process.ts:74:20)
    at process._tickCallback (internal/process/next_tick.js:68:7)
2020-09-24 05:35:19 - warn: Error setting process active TypeError: Update document requires atomic operators
TypeError: Update document requires atomic operators
    at new UpdateOneOperation (/home/jordanlanch/WolfBot/node_modules/mongodb/lib/operations/update_one.js:12:13)
    at Collection.updateOne (/home/jordanlanch/WolfBot/node_modules/mongodb/lib/collection.js:758:5)
    at collection.findOne.then (/home/jordanlanch/WolfBot/node_modules/@ekliptor/bit-models/models/Process.ts:74:20)
    at process._tickCallback (internal/process/next_tick.js:68:7)
2020-09-24 05:35:24 - warn: Error setting process active TypeError: Update document requires atomic operators
TypeError: Update document requires atomic operators
    at new UpdateOneOperation (/home/jordanlanch/WolfBot/node_modules/mongodb/lib/operations/update_one.js:12:13)
    at Collection.updateOne (/home/jordanlanch/WolfBot/node_modules/mongodb/lib/collection.js:758:5)
    at collection.findOne.then (/home/jordanlanch/WolfBot/node_modules/@ekliptor/bit-models/models/Process.ts:74:20)
    at process._tickCallback (internal/process/next_tick.js:68:7)
2020-09-24 05:35:28 - warn: Error setting process active TypeError: Update document requires atomic operators
TypeError: Update document requires atomic operators
    at new UpdateOneOperation (/home/jordanlanch/WolfBot/node_modules/mongodb/lib/operations/update_one.js:12:13)
    at Collection.updateOne (/home/jordanlanch/WolfBot/node_modules/mongodb/lib/collection.js:758:5)
    at collection.findOne.then (/home/jordanlanch/WolfBot/node_modules/@ekliptor/bit-models/models/Process.ts:74:20)
    at process._tickCallback (internal/process/next_tick.js:68:7)
2020-09-24 05:35:32 - warn: Error setting process active TypeError: Update document requires atomic operators
TypeError: Update document requires atomic operators
    at new UpdateOneOperation (/home/jordanlanch/WolfBot/node_modules/mongodb/lib/operations/update_one.js:12:13)
    at Collection.updateOne (/home/jordanlanch/WolfBot/node_modules/mongodb/lib/collection.js:758:5)
    at collection.findOne.then (/home/jordanlanch/WolfBot/node_modules/@ekliptor/bit-models/models/Process.ts:74:20)
    at process._tickCallback (internal/process/next_tick.js:68:7)
2020-09-24 05:35:36 - warn: Error setting process active TypeError: Update document requires atomic operators
TypeError: Update document requires atomic operators
    at new UpdateOneOperation (/home/jordanlanch/WolfBot/node_modules/mongodb/lib/operations/update_one.js:12:13)
    at Collection.updateOne (/home/jordanlanch/WolfBot/node_modules/mongodb/lib/collection.js:758:5)
    at collection.findOne.then (/home/jordanlanch/WolfBot/node_modules/@ekliptor/bit-models/models/Process.ts:74:20)
    at process._tickCallback (internal/process/next_tick.js:68:7)
2020-09-24 05:35:37 - debug: Secure request: /backtest
2020-09-24 05:35:38 - debug: Secure request: /css/style.css?v=8
2020-09-24 05:35:39 - debug: Secure request: /css/libs/bootstrap-datetimepicker.min.css
2020-09-24 05:35:39 - debug: Secure request: /icons/fav/icon_114.png
2020-09-24 05:35:41 - warn: Error setting process active TypeError: Update document requires atomic operators
TypeError: Update document requires atomic operators
    at new UpdateOneOperation (/home/jordanlanch/WolfBot/node_modules/mongodb/lib/operations/update_one.js:12:13)
    at Collection.updateOne (/home/jordanlanch/WolfBot/node_modules/mongodb/lib/collection.js:758:5)
    at collection.findOne.then (/home/jordanlanch/WolfBot/node_modules/@ekliptor/bit-models/models/Process.ts:74:20)
    at process._tickCallback (internal/process/next_tick.js:68:7)
2020-09-24 05:35:41 - debug: Secure request: /locales/en.json?v=0.1.0
2020-09-24 05:35:42 - warn: Error setting process active TypeError: Update document requires atomic operators
TypeError: Update document requires atomic operators
    at new UpdateOneOperation (/home/jordanlanch/WolfBot/node_modules/mongodb/lib/operations/update_one.js:12:13)
    at Collection.updateOne (/home/jordanlanch/WolfBot/node_modules/mongodb/lib/collection.js:758:5)
    at collection.findOne.then (/home/jordanlanch/WolfBot/node_modules/@ekliptor/bit-models/models/Process.ts:74:20)
    at process._tickCallback (internal/process/next_tick.js:68:7)
2020-09-24 05:35:43 - debug: Secure request: /css/libs/bootstrap-datetimepicker.min.css
2020-09-24 05:35:43 - debug: Secure request: /js/libs/moment/moment.min.js
2020-09-24 05:35:44 - debug: Secure request: /js/libs/bootstrap-datetimepicker.min.js
2020-09-24 05:35:44 - warn: Error setting process active TypeError: Update document requires atomic operators
TypeError: Update document requires atomic operators
    at new UpdateOneOperation (/home/jordanlanch/WolfBot/node_modules/mongodb/lib/operations/update_one.js:12:13)
    at Collection.updateOne (/home/jordanlanch/WolfBot/node_modules/mongodb/lib/collection.js:758:5)
    at collection.findOne.then (/home/jordanlanch/WolfBot/node_modules/@ekliptor/bit-models/models/Process.ts:74:20)
    at process._tickCallback (internal/process/next_tick.js:68:7)
2020-09-24 05:35:48 - warn: Error setting process active TypeError: Update document requires atomic operators
TypeError: Update document requires atomic operators
    at new UpdateOneOperation (/home/jordanlanch/WolfBot/node_modules/mongodb/lib/operations/update_one.js:12:13)
    at Collection.updateOne (/home/jordanlanch/WolfBot/node_modules/mongodb/lib/collection.js:758:5)
    at collection.findOne.then (/home/jordanlanch/WolfBot/node_modules/@ekliptor/bit-models/models/Process.ts:74:20)
    at process._tickCallback (internal/process/next_tick.js:68:7)
2020-09-24 05:35:53 - warn: Error setting process active TypeError: Update document requires atomic operators
TypeError: Update document requires atomic operators
    at new UpdateOneOperation (/home/jordanlanch/WolfBot/node_modules/mongodb/lib/operations/update_one.js:12:13)
    at Collection.updateOne (/home/jordanlanch/WolfBot/node_modules/mongodb/lib/collection.js:758:5)
    at collection.findOne.then (/home/jordanlanch/WolfBot/node_modules/@ekliptor/bit-models/models/Process.ts:74:20)
    at process._tickCallback (internal/process/next_tick.js:68:7)
2020-09-24 05:35:55 - verbose: Updating portfolio of 1 exchanges in RealTimeTrader
2020-09-24 05:35:58 - warn: Error setting process active TypeError: Update document requires atomic operators
TypeError: Update document requires atomic operators
    at new UpdateOneOperation (/home/jordanlanch/WolfBot/node_modules/mongodb/lib/operations/update_one.js:12:13)
    at Collection.updateOne (/home/jordanlanch/WolfBot/node_modules/mongodb/lib/collection.js:758:5)
    at collection.findOne.then (/home/jordanlanch/WolfBot/node_modules/@ekliptor/bit-models/models/Process.ts:74:20)
    at process._tickCallback (internal/process/next_tick.js:68:7)
2020-09-24 05:35:58 - verbose: Checked Bitfinex margin collateral (for possible margin call): 1
2020-09-24 05:35:59 - warn: Error setting process active TypeError: Update document requires atomic operators
TypeError: Update document requires atomic operators
    at new UpdateOneOperation (/home/jordanlanch/WolfBot/node_modules/mongodb/lib/operations/update_one.js:12:13)
    at Collection.updateOne (/home/jordanlanch/WolfBot/node_modules/mongodb/lib/collection.js:758:5)
    at collection.findOne.then (/home/jordanlanch/WolfBot/node_modules/@ekliptor/bit-models/models/Process.ts:74:20)
    at process._tickCallback (internal/process/next_tick.js:68:7)
2020-09-24 05:36:00 - verbose: WebSocket connection closed with code 1001: 
2020-09-24 05:36:01 - warn: Error setting process active TypeError: Update document requires atomic operators
TypeError: Update document requires atomic operators
    at new UpdateOneOperation (/home/jordanlanch/WolfBot/node_modules/mongodb/lib/operations/update_one.js:12:13)
    at Collection.updateOne (/home/jordanlanch/WolfBot/node_modules/mongodb/lib/collection.js:758:5)
    at collection.findOne.then (/home/jordanlanch/WolfBot/node_modules/@ekliptor/bit-models/models/Process.ts:74:20)
    at process._tickCallback (internal/process/next_tick.js:68:7)
2020-09-24 05:36:02 - verbose: WebSocket connection closed with code 1001: 
2020-09-24 05:36:06 - warn: Error setting process active TypeError: Update document requires atomic operators
TypeError: Update document requires atomic operators
    at new UpdateOneOperation (/home/jordanlanch/WolfBot/node_modules/mongodb/lib/operations/update_one.js:12:13)
    at Collection.updateOne (/home/jordanlanch/WolfBot/node_modules/mongodb/lib/collection.js:758:5)
    at collection.findOne.then (/home/jordanlanch/WolfBot/node_modules/@ekliptor/bit-models/models/Process.ts:74:20)
    at process._tickCallback (internal/process/next_tick.js:68:7)
2020-09-24 05:36:06 - verbose: Fetched ticker of Bitfinex
2020-09-24 05:36:09 - debug: Secure request: /backtest
2020-09-24 05:36:09 - debug: Secure request: /css/style.css?v=8
2020-09-24 05:36:10 - debug: Secure request: /js/libs/functions.js
2020-09-24 05:36:10 - debug: Secure request: /css/bootstrap-multiselect.css
2020-09-24 05:36:10 - debug: Secure request: /css/libs/bootstrap-datetimepicker.min.css
2020-09-24 05:36:10 - debug: Secure request: /js/polyfills.js
2020-09-24 05:36:10 - debug: Secure request: /js/libs/i18next.min.js
2020-09-24 05:36:10 - debug: Secure request: /js/libs/Chart.bundle.js
2020-09-24 05:36:10 - debug: Secure request: /js/libs/eventemitter2.js
2020-09-24 05:36:10 - debug: Secure request: /js/libs/i18nextXHRBackend.min.js
2020-09-24 05:36:10 - debug: Secure request: /js/libs/bootstrap-multiselect.js
2020-09-24 05:36:10 - debug: Secure request: /js/libs/ace/ace.js
2020-09-24 05:36:10 - debug: Secure request: /js/libs/jquery.dataTables.js
2020-09-24 05:36:10 - debug: Secure request: /js/libs/dataTables.bootstrap.js
2020-09-24 05:36:10 - debug: Secure request: /js/constants.js
2020-09-24 05:36:10 - debug: Secure request: /js/libs/helper.js
2020-09-24 05:36:10 - debug: Secure request: /js/libs/browserutils.js
2020-09-24 05:36:10 - debug: Secure request: /js/libs/tv/charting_library.min.js
2020-09-24 05:36:10 - verbose: Error sending WebSocket data WebSocket is not open: readyState 3 (CLOSED)
2020-09-24 05:36:10 - verbose: Error sending WebSocket data WebSocket is not open: readyState 3 (CLOSED)
2020-09-24 05:36:10 - verbose: Error sending WebSocket data WebSocket is not open: readyState 3 (CLOSED)
2020-09-24 05:36:10 - verbose: Error sending WebSocket data WebSocket is not open: readyState 3 (CLOSED)
2020-09-24 05:36:10 - verbose: Error sending WebSocket data WebSocket is not open: readyState 3 (CLOSED)
2020-09-24 05:36:10 - debug: Secure request: /js/bundle.js?v=8
2020-09-24 05:36:11 - warn: Error setting process active TypeError: Update document requires atomic operators
TypeError: Update document requires atomic operators
    at new UpdateOneOperation (/home/jordanlanch/WolfBot/node_modules/mongodb/lib/operations/update_one.js:12:13)
    at Collection.updateOne (/home/jordanlanch/WolfBot/node_modules/mongodb/lib/collection.js:758:5)
    at collection.findOne.then (/home/jordanlanch/WolfBot/node_modules/@ekliptor/bit-models/models/Process.ts:74:20)
    at process._tickCallback (internal/process/next_tick.js:68:7)
2020-09-24 05:36:11 - verbose: 1min BITFINEX candle USD_ETH at 2020-09-24 05:35:00: high 325.92972488, low 325.57000000, close 325.92972488, volume 11.63720949, trades 4
2020-09-24 05:36:11 - verbose: WebSocket connection closed with code 1006: 
2020-09-24 05:36:11 - debug: Secure request: /icons/fav/icon_114.png
2020-09-24 05:36:11 - debug: Secure request: /locales/en.json?v=0.1.0
2020-09-24 05:36:12 - warn: Error setting process active TypeError: Update document requires atomic operators
TypeError: Update document requires atomic operators
    at new UpdateOneOperation (/home/jordanlanch/WolfBot/node_modules/mongodb/lib/operations/update_one.js:12:13)
    at Collection.updateOne (/home/jordanlanch/WolfBot/node_modules/mongodb/lib/collection.js:758:5)
    at collection.findOne.then (/home/jordanlanch/WolfBot/node_modules/@ekliptor/bit-models/models/Process.ts:74:20)
    at process._tickCallback (internal/process/next_tick.js:68:7)
2020-09-24 05:36:13 - verbose: Error sending WebSocket data WebSocket is not open: readyState 3 (CLOSED)
2020-09-24 05:36:13 - verbose: Error sending WebSocket data WebSocket is not open: readyState 3 (CLOSED)
2020-09-24 05:36:13 - verbose: Error sending WebSocket data WebSocket is not open: readyState 3 (CLOSED)
2020-09-24 05:36:13 - verbose: Error sending WebSocket data WebSocket is not open: readyState 3 (CLOSED)
2020-09-24 05:36:13 - verbose: Error sending WebSocket data WebSocket is not open: readyState 3 (CLOSED)
2020-09-24 05:36:13 - verbose: 1min BITFINEX candle USD_BTC at 2020-09-24 05:35:00: high 10319.00000000, low 10319.00000000, close 10319.00000000, volume 0.11262808, trades 3
2020-09-24 05:36:14 - debug: Secure request: /fonts/fontawesome-webfont.woff2?v=4.7.0
2020-09-24 05:36:14 - debug: Secure request: /js/libs/moment/moment.min.js
2020-09-24 05:36:14 - debug: Secure request: /css/libs/bootstrap-datetimepicker.min.css
2020-09-24 05:36:14 - debug: Secure request: /js/libs/bootstrap-datetimepicker.min.js
2020-09-24 05:36:15 - warn: Error setting process active TypeError: Update document requires atomic operators
TypeError: Update document requires atomic operators
    at new UpdateOneOperation (/home/jordanlanch/WolfBot/node_modules/mongodb/lib/operations/update_one.js:12:13)
    at Collection.updateOne (/home/jordanlanch/WolfBot/node_modules/mongodb/lib/collection.js:758:5)
    at collection.findOne.then (/home/jordanlanch/WolfBot/node_modules/@ekliptor/bit-models/models/Process.ts:74:20)
    at process._tickCallback (internal/process/next_tick.js:68:7)
2020-09-24 05:36:17 - warn: Error setting process active TypeError: Update document requires atomic operators
TypeError: Update document requires atomic operators
    at new UpdateOneOperation (/home/jordanlanch/WolfBot/node_modules/mongodb/lib/operations/update_one.js:12:13)
    at Collection.updateOne (/home/jordanlanch/WolfBot/node_modules/mongodb/lib/collection.js:758:5)
    at collection.findOne.then (/home/jordanlanch/WolfBot/node_modules/@ekliptor/bit-models/models/Process.ts:74:20)
    at process._tickCallback (internal/process/next_tick.js:68:7)
2020-09-24 05:36:18 - warn: Error setting process active TypeError: Update document requires atomic operators
TypeError: Update document requires atomic operators
    at new UpdateOneOperation (/home/jordanlanch/WolfBot/node_modules/mongodb/lib/operations/update_one.js:12:13)
    at Collection.updateOne (/home/jordanlanch/WolfBot/node_modules/mongodb/lib/collection.js:758:5)
    at collection.findOne.then (/home/jordanlanch/WolfBot/node_modules/@ekliptor/bit-models/models/Process.ts:74:20)
    at process._tickCallback (internal/process/next_tick.js:68:7)
2020-09-24 05:36:19 - warn: Error setting process active TypeError: Update document requires atomic operators
TypeError: Update document requires atomic operators
    at new UpdateOneOperation (/home/jordanlanch/WolfBot/node_modules/mongodb/lib/operations/update_one.js:12:13)
    at Collection.updateOne (/home/jordanlanch/WolfBot/node_modules/mongodb/lib/collection.js:758:5)
    at collection.findOne.then (/home/jordanlanch/WolfBot/node_modules/@ekliptor/bit-models/models/Process.ts:74:20)
    at process._tickCallback (internal/process/next_tick.js:68:7)
2020-09-24 05:36:20 - warn: Error setting process active TypeError: Update document requires atomic operators
TypeError: Update document requires atomic operators
    at new UpdateOneOperation (/home/jordanlanch/WolfBot/node_modules/mongodb/lib/operations/update_one.js:12:13)
    at Collection.updateOne (/home/jordanlanch/WolfBot/node_modules/mongodb/lib/collection.js:758:5)
    at collection.findOne.then (/home/jordanlanch/WolfBot/node_modules/@ekliptor/bit-models/models/Process.ts:74:20)
    at process._tickCallback (internal/process/next_tick.js:68:7)
2020-09-24 05:36:21 - warn: Error setting process active TypeError: Update document requires atomic operators
TypeError: Update document requires atomic operators
    at new UpdateOneOperation (/home/jordanlanch/WolfBot/node_modules/mongodb/lib/operations/update_one.js:12:13)
    at Collection.updateOne (/home/jordanlanch/WolfBot/node_modules/mongodb/lib/collection.js:758:5)
    at collection.findOne.then (/home/jordanlanch/WolfBot/node_modules/@ekliptor/bit-models/models/Process.ts:74:20)
    at process._tickCallback (internal/process/next_tick.js:68:7)
2020-09-24 05:36:23 - warn: Error setting process active TypeError: Update document requires atomic operators
TypeError: Update document requires atomic operators
```

**Comment by Ekliptor** [comment]
you are running old/inconsistent dependencies - specifically bit-models for WolfBot

please run `yarn install` again and make sure bit-models is at latest version.
